services:
  redis:
    image: redis:latest
    container_name: redis-server
    networks:
      - sbc-net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:

networks:
  sbc-net:
    external: true